In [2]:
import numpy as np

In [3]:
grades = np.array([85,90,88,92,95,80,75,98,89,83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [4]:
mean = np.mean(grades)
print(mean)

87.5


In [5]:
median = np.median(grades)
print(median)

88.5


In [6]:
std = np.std(grades)
print(std)

6.591661399070799


In [7]:
minimum = np.min(grades)
print(minimum)

75


In [8]:
maximum = np.max(grades)
print(maximum)

98


In [10]:
grades.sort()
print(grades)

[75 80 83 85 88 89 90 92 95 98]


In [11]:
index_highest = np.argmax(grades)
print(index_highest)

9


In [15]:
greater_than_90 = np.where(grades > 90)
print(np.count_nonzero(greater_than_90))

3


In [17]:
percentage_above_90 = (np.mean(grades > 90) * 100)
print(percentage_above_90)

30.0


In [18]:
high_performers = grades[grades > 90]
print(high_performers)

[92 95 98]


In [19]:
passing_grades = grades[grades > 75]
print(passing_grades)

[80 83 85 88 89 90 92 95 98]
